urls_project/accounts/urls.py
from django.urls import re_path, path,include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'


urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(),name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('details/<pk>/',views.UserDetailsView.as_view(),name='user_details'),
    path('',include('packs.urls')),
]

urls_project/links/urls.py
from tkinter import N
from django.urls import path
from . import views


app_name = 'links'

urlpatterns = [
    path('<username>/<slug>', views.LinksListView.as_view(),name='list'),
    path('create/', views.LinkCreateView.as_view(),name='create'),
    path('update/<username>/<slug>', views.LinkUpdateView.as_view(),name='update'),
    path('delete/<username>/<slug>', views.LinkDeleteView.as_view(),name='delete'),
]

urls_project/packs/urls.py
from django.urls import path

from . import views

app_name = 'packs'

urlpatterns = [
    path("<str:username>/", views.PackageListView.as_view(), name="package_list"),
    path("delete/<int:pk>", views.PackageDeleteView.as_view(), name="package_delete"),
    path("update/<int:pk>", views.PackageUpdateView.as_view(), name="package_update"),
    path("create/<str:username>/", views.PackageCreateView.as_view(), name="package_create"),
]

urls_project/urls_project/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('about/', views.AboutPage.as_view(), name='about'),
    path('admin/', admin.site.urls),
    
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('packs/', include('packs.urls')),
    path('links/', include('links.urls')),
   # path('<str:username>/',PackageListView.as_view(),name='dashboard'),
]

urls_project/templates/about.html
{% extends 'base.html' %}

{% block content %}

<div class="ui segments">
    <div class="ui segment">
        <h2>About us</h2>
    </div>
    <div class="ui segment">
        <p>main purpose is saving link on web</p>

    </div>
</div>

{% endblock  %}

urls_project/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Base</title>
    <!-- CSS only -->
    <link rel="stylesheet"  type ="text/css" href="{% static '..//static/semantic-ui/semantic.css' %}">
</head>
<body style="background-color:#eaf4f4;" >
    <div class="ui inverted segment">
        <div class="ui inverted secondary menu">
          <a class="item" href="{% url 'home' %}"><i class="linkify icon"></i>myURLs</a>
          <a class="item" href="{% url 'about' %}"><i class="info icon"></i>About</a>
          <div class="right menu">
            {% if user.is_authenticated %}  
              <a class="item" href="{% url 'packs:package_list' username=user.username%}">My Packages</a> 
              <a class="item" href="{% url 'packs:package_create' username=user.username%}">Create Package</a>          
              <a class="item" href="{% url 'links:create' %}">Create Link</a>     
              <a class="item" href="{% url 'accounts:logout' %}">Logout</a>
              <a class="item " href="">Welcome {{user.username}}</a>
            {% else %} 
               <a class="item" href="{% url 'accounts:signup' %}"><i class="signup alternate icon"></i>Signup</a> 
               <a class="item" href="{% url 'accounts:login' %}"><i class="sign in alternate icon"></i>Login</a>
            {% endif %}
          </div>
        </div>
      </div>

    
    <div class="ui container">
        <div class="ui grid">
            <div class="twelve wide column">{% block content %}{% endblock  %}</div>
            <div class="four wide column"><div class="ui vertical rectangle test ad" data-text="Vertical Rectangle"></div></div>
          </div>
        
    </div>
            
          
    
    
</body>
</html>

urls_project/templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="ui segments">
    <div class="ui segment">
        <h1>index</h1>
    </div>
    <div class="ui segment">
        <p>more on dummy info</p>
    </div>
    
</div>

{% endblock  %}