urls_project/links/urls.py
from tkinter import N
from django.urls import path
from . import views


app_name = 'links'

urlpatterns = [
    path('<username>/<slug>', views.LinksListView.as_view(),name='list'),
    path('create/', views.LinkCreateView.as_view(),name='create'),
    path('update/<username>/<slug>', views.LinkUpdateView.as_view(),name='update'),
    path('delete/<username>/<slug>', views.LinkDeleteView.as_view(),name='delete'),
]

urls_project/packs/urls.py
from django.urls import path

from . import views

app_name = 'packs'

urlpatterns = [
    path("<str:username>/", views.PackageListView.as_view(), name="package_list"),
    path("delete/<int:pk>", views.PackageDeleteView.as_view(), name="package_delete"),
    path("update/<int:pk>", views.PackageUpdateView.as_view(), name="package_update"),
    path("create/<str:username>/", views.PackageCreateView.as_view(), name="package_create"),
]

urls_project/urls_project/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('about/', views.AboutPage.as_view(), name='about'),
    path('admin/', admin.site.urls),
    
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('packs/', include('packs.urls')),
    path('links/', include('links.urls')),
   # path('<str:username>/',PackageListView.as_view(),name='dashboard'),
]

urls_project/packs/models.py
from django.db import models
from django.urls import reverse,reverse_lazy

from django.utils.text import slugify
from django.contrib.auth import get_user_model

# Create your models here.
User = get_user_model()

class Package(models.Model):
    user = models.ForeignKey(User, related_name='packages', on_delete=models.CASCADE)
    name = models.CharField(max_length=256,unique=True)
    description = models.CharField(max_length=256)
    slug = models.SlugField(null=False, unique=True)
    
    def save(self,*args, **kwargs) -> None:
        self.slug = slugify(self.name)
        super().save(*args,**kwargs)

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse("packs:package_list", kwargs={"username": self.user.username})
        

urls_project/packs/forms.py
from dataclasses import field, fields
from django import forms
from .models import Package

class PackageForm(forms.ModelForm):

    class Meta():
        model = Package
        fields = ('name','description')

urls_project/packs/views.py
from struct import pack
from django.shortcuts import get_object_or_404
from django.views import generic

from links.models import Link
from .models import Package
from django.contrib.auth.mixins import LoginRequiredMixin
from braces.views import SelectRelatedMixin
from django.urls import reverse_lazy
from django.http import Http404
from django.contrib import messages
from . import forms
from django.contrib.auth import get_user_model
User = get_user_model()

# Create your views here.


class PackageListView(LoginRequiredMixin, SelectRelatedMixin, generic.ListView):
    model = Package
    select_related = ('user', 'package')
    template_name: str = 'package_list.html'

    def get_queryset(self):
        try:
            self.package_user = User.objects.prefetch_related("packages").get(
                username__iexact=self.kwargs.get("username")
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.package_user.packages.all()

class PackageCreateView(generic.CreateView):
    model = Package
    fields = ('name', 'description')
    template_name: str = 'packs/package_create.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class PackageUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Package
    template_name: str = 'packs/package_update.html'
    redirect_field_name = '/'
    form_class = forms.PackageForm

class PackageDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Package
    template_name: str = 'packs/package_delete.html'
    messages = ()
    success_url = reverse_lazy("home")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Post Deleted")
        return super().delete(*args, **kwargs)

urls_project/packs/templates/packs/package_create.html
{% extends "base.html" %}

{% block content %}
<div class="ui segments">
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <div class="ui segment">
        <h4>Create A New pack</h4>
    </div>
    <div class="ui segment">
        <form method="POST" action="{% url 'packs:package_create' username=user.username %}" class="ui form">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Create Package" class="ui positive button">
        </form>
    </div>
</div>

{% endblock %}

urls_project/packs/templates/packs/package_delete.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block content %}
<div class="ui segments">
    <div class="ui segment">
        <h3>Are you sure you want to delete this {{package}}?</h3>
    </div>
    <div class="ui segment">
        {% if user.is_authenticated and package.user == user %}
                <form method="POST">
                    {% csrf_token %}
                    <input type="submit" value="Delete" class="ui negative button">
                    <a href="{% url 'packs:package_list' username=user.username %}" class="ui positive button">Cancel</a>
                </form>
        {% endif %}
    </div>
</div>

{% endblock content %}
    

urls_project/packs/templates/packs/package_list.html
<!DOCTYPE html>

{% extends 'base.html' %}

{% block content %}

<div class="ui segments">
    <div class="ui segment">
        <h3><i class="folder icon"></i>Here is your all packages!</h3>
    </div>
    <div class="ui segment">
        <div class="ui cards">
            {% for pack in object_list %}
            <div class="card" style="background-color:#eaf4f4;">
                
                <div class="content">
                  <a href="{% url 'links:list' username=user.username slug=pack.slug%}">
                  <div class="header">
                    <h2>
                    <i class="folder open outline icon"></i>{{pack.name}}</h2></div></a>
                  <div class="meta"><i class="paperclip icon"></i>{{pack.urls.count}} links</div>
                  <div class="description">
                    <p>{{pack.description}}</p>
                  </div>
                </div>
                
                <div class="extra content">
                    <div class="ui buttons">
                        <a href="{% url 'packs:package_update' pk=pack.pk %}">
                            <button class="ui primary  button">Update</button>
                        </a>                    
                        <div class="or"></div>
                        <a href="{% url 'packs:package_delete' pk=pack.pk %}">
                            <button class="ui negative button" >Delete</button>
                        </a>
                      </div>
                  </div>
            </div>

            {% endfor %}
        
        
            </div>
    
        </div>
    
</div>

{% endblock  %}
    

urls_project/packs/templates/packs/package_update.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block content %}
<div class="ui segments">
    <div class="ui segment">
        <h3>Are you sure you want to update this {{package}}?</h3>
    </div>
    <div class="ui segment">
        {% if user.is_authenticated and package.user == user %}
                <form method="POST" class="ui form">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="Update" class="ui positive button">
                    <a href="{% url 'packs:package_list' username=user.username %}" class="ui primary button">Cancel</a>
                </form>
        {% endif %}
    </div>
</div>

{% endblock content %}